version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootinho
      MYSQL_DATABASE: rooto
      MYSQL_USER: nodinho
      MYSQL_PASSWORD: rootinho
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    command: 
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
 
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "-c", "python wait-for-it.py db 3306 60 && npm start"]


volumes:
  db_data: {}

networks:
  default:
     attachable: true